name             'apt'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures apt'
long_description 'Installs/Configures apt'
version          '0.1.0'
