name             'vpn'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures vpn'
long_description 'Installs/Configures vpn'
version          '0.1.0'
