name             'kiosk'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures kiosk'
long_description 'Installs/Configures kiosk'
version          '0.1.0'
